/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import PatientManagementModel.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author jjbrewer
 */
public class AppointmentForm extends javax.swing.JFrame {
    
    Appointment appointment;
    MedacineManager medacineManager;
    /**
     * Creates new form AppointmentForm
     */
    public AppointmentForm(Appointment appointment, MedacineManager medacineManager) 
    {
        initComponents();
        this.appointment = appointment;
        this.medacineManager = medacineManager;
        appointmentFormCreated();
    }
    
    public void appointmentFormCreated()
    {
        populateComboBox();
        lblDoctorAddress.setText(appointment.getDoctor().getAddress());
        lblDoctorName.setText(appointment.getDoctor().getGivenName() + " " + appointment.getDoctor().getSurname());
        lblPatientAddress.setText(appointment.getPatient().getAddress());;
        lblPatientAge.setText(Integer.toString(appointment.getPatient().GetDOB()));
        lblPatientGender.setText(appointment.getPatient().GetGender());
        lblPatientName.setText(appointment.getPatient().getGivenName() + " " + appointment.getPatient().getSurname());
    }
    
    public void populateComboBox()
    {
        List<Medacine> medacine = medacineManager.getMedacineList();
        List<String> ls = new ArrayList<String>();
        if(medacine != null)
        {
            for(Medacine med : medacine)
            {
                ls.add(med.getName());
            }

            cmbxMedacine.setModel(new DefaultComboBoxModel(ls.toArray()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctor = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        lblDoctorAddress = new javax.swing.JLabel();
        lblPatientAddress = new javax.swing.JLabel();
        lblPatient = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientGender = new javax.swing.JLabel();
        lblPatientAge = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaNote = new javax.swing.JTextArea();
        btnMakeNote = new javax.swing.JButton();
        cmbxMedacine = new javax.swing.JComboBox<>();
        spnQuantity = new javax.swing.JSpinner();
        txtDosage = new javax.swing.JTextField();
        btnMakePerscription = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDoctor.setText("Doctor");

        lblDoctorName.setText("Name");

        lblDoctorAddress.setText("Address");

        lblPatientAddress.setText("Address");

        lblPatient.setText("Patient");

        lblPatientName.setText("Name");

        lblPatientGender.setText("Gender");

        lblPatientAge.setText("Age");

        txtAreaNote.setColumns(20);
        txtAreaNote.setRows(5);
        jScrollPane3.setViewportView(txtAreaNote);

        btnMakeNote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMakeNote.setText("Make note");
        btnMakeNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeNoteActionPerformed(evt);
            }
        });

        cmbxMedacine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxMedacine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spnQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDosage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDosage.setText("Dosage");

        btnMakePerscription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMakePerscription.setText("Make perscription");
        btnMakePerscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePerscriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatient)
                            .addComponent(lblPatientName)
                            .addComponent(lblPatientAddress)
                            .addComponent(lblPatientGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDoctor)
                            .addComponent(lblDoctorName)
                            .addComponent(lblDoctorAddress))
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPatientAge)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMakeNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMakePerscription)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbxMedacine, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDoctor)
                        .addGap(18, 18, 18)
                        .addComponent(lblDoctorName)
                        .addGap(18, 18, 18)
                        .addComponent(lblDoctorAddress))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPatientName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPatientAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPatientGender)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPatientAge)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMakeNote)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDosage)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(cmbxMedacine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnMakePerscription)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakeNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeNoteActionPerformed
        // TODO add your handling code here:
        appointment.makeNote(txtAreaNote.getText());
    }//GEN-LAST:event_btnMakeNoteActionPerformed

    private void btnMakePerscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePerscriptionActionPerformed
        // TODO add your handling code here:
        int quantity = 0;
        try
        {
            spnQuantity.commitEdit();
        }
        catch(java.text.ParseException e)
        {
            quantity = (Integer) spnQuantity.getValue();
        }
        Perscription newPerscription = new Perscription(medacineManager.getMedacineList().get(cmbxMedacine.getSelectedIndex()), appointment.getDoctor(), appointment.getPatient(), quantity, txtDosage.getText());
        appointment.addPerscription(newPerscription);
    }//GEN-LAST:event_btnMakePerscriptionActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakeNote;
    private javax.swing.JButton btnMakePerscription;
    private javax.swing.JComboBox<String> cmbxMedacine;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblDoctorAddress;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPatientAddress;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextArea txtAreaNote;
    private javax.swing.JTextField txtDosage;
    // End of variables declaration//GEN-END:variables
}
